# Generated by Django 3.2.4 on 2022-12-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221207_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactus',
        ),
    ]
