# Generated by Django 3.2.4 on 2022-12-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_contact_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/profile/')),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
        ),
    ]
