# Generated by Django 3.2.4 on 2022-12-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/feedback/')),
                ('email', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
