# Generated by Django 3.2.4 on 2023-05-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
