# Generated by Django 3.2.4 on 2023-05-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='Name',
        ),
    ]
