# Generated by Django 3.2.4 on 2023-05-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_name_blog_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='static/blog/')),
                ('Data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
