# Generated by Django 3.2.4 on 2023-05-02 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230501_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourblog',
            name='Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
