# Generated by Django 3.2.4 on 2023-05-02 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_ourblog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='mynews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstitle', models.TextField()),
                ('newsdec', models.TextField()),
                ('newsimage', models.ImageField(upload_to='static/news/')),
                ('newsdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('newscategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
    ]
