# Generated by Django 3.2.4 on 2023-05-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_mynews'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_reporter',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/profile_reporter/')),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
        ),
    ]
