# Generated by Django 3.2.4 on 2023-05-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_signup_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynews',
            name='newsreporter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
