# Generated by Django 3.2.4 on 2023-05-06 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_mynews_newsreporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynews',
            name='newscategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newscate', to='user.category'),
        ),
        migrations.AlterField(
            model_name='mynews',
            name='newsreporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsreport', to='user.signup_reporter'),
        ),
    ]
