# Generated by Django 3.2.4 on 2023-05-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_mynews_newstitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynews',
            name='newstitle',
            field=models.TextField(),
        ),
    ]
