# Generated by Django 3.2.4 on 2023-07-06 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20230524_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynews',
            name='newscategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category'),
        ),
        migrations.AlterField(
            model_name='mynews',
            name='newsreporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup_reporter'),
        ),
    ]
